### ISSUE TITLE
ERROR! An error occured while running jhipster-primeng-blueprint:languages#askForLanguages

### ISSUE THREAD

**Issue by eanunezt** [tailosoft/jhipster-primeng-blueprint#66]
Please help me with this error:

Node version: v18.17.1
jhipster: npm link from https://github.com/yelhouti/generator-jhipster/tree/composite-key

PS C:\Users\enune\Documents\git\jhipster.primeng\p3i.app.web2> npm install -g generator-jhipster-primeng-blueprint
....
PS C:\Users\enune\Documents\git\jhipster.primeng\p3i.app.web2> npm link generator-jhipster

added 1 package in 33s

1 package is looking for funding
  run `npm fund` for details
PS C:\Users\enune\Documents\git\jhipster.primeng\p3i.app.web2> jhipster --blueprint primeng-blueprint --skip-server
WARNING! Since JHipster v8, the jhipster command will not use the locally installed generator-jhipster.
    If you want to execute the locally installed generator-jhipster, run: npx jhipster
INFO! No custom sharedOptions found within blueprint: generator-jhipster-primeng-blueprint at C:\Program Files\nodejs\node_modules\generator-jhipster-primeng-blueprint
INFO! No custom commands found within blueprint: generator-jhipster-primeng-blueprint at C:\Program Files\nodejs\node_modules\generator-jhipster-primeng-blueprint

        ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
        ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
        ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
  ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
  ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
   ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝
                            https://www.jhipster.tech
Welcome to JHipster v8.0.0-beta.1

WARNING! --blueprint option is deprecated. Please use --blueprints instead
 _______________________________________________________________________________________________________________

  Documentation for creating an application is at https://www.jhipster.tech/creating-an-app/

  Application files will be generated in folder: C:\Users\enune\Documents\git\jhipster.primeng\p3i.app.web2
 _______________________________________________________________________________________________________________

? What is the base name of your application? P3IWeb
? Which *type* of application would you like to create? Monolithic application (recommended for simple projects)
? Which *Framework* would you like to use for the client? Angular
? Do you want to generate the admin UI? Yes
? Would you like to use a Bootswatch theme (https://bootswatch.com/)? Materia
? Choose a Bootswatch variant navbar theme (https://bootswatch.com/)? Primary
? Would you like to enable internationalization support? Yes
? Please choose the native language of the application Spanish
ERROR! An error occured while running jhipster-primeng-blueprint:languages#askForLanguages
ERROR! ERROR! Cannot read properties of undefined (reading 'filter')
TypeError: Cannot read properties of undefined (reading 'filter')
    at Object.choices (file:///C:/Users/enune/AppData/Roaming/nvm/v18.17.1/node_modules/generator-jhipster-primeng-blueprint/node_modules/generator-jhipster/dist/generators/languages/prompts.mjs:58:59)
    at C:\Users\enune\Documents\git\jhipster.primeng\generator-jhipster\node_modules\run-async\index.js:91:25
    at new Promise (<anonymous>)
    at C:\Users\enune\Documents\git\jhipster.primeng\generator-jhipster\node_modules\run-async\index.js:32:19
    at Module.fetchAsyncQuestionProperty (file:///C:/Users/enune/Documents/git/jhipster.primeng/generator-jhipster/node_modules/inquirer/lib/utils/utils.js:19:29)
    at file:///C:/Users/enune/Documents/git/jhipster.primeng/generator-jhipster/node_modules/inquirer/lib/ui/prompt.js:95:17
    at doInnerSub (C:\Users\enune\Documents\git\jhipster.primeng\generator-jhipster\node_modules\rxjs\dist\cjs\internal\operators\mergeInternals.js:22:31)
    at outerNext (C:\Users\enune\Documents\git\jhipster.primeng\generator-jhipster\node_modules\rxjs\dist\cjs\internal\operators\mergeInternals.js:17:70)
    at OperatorSubscriber._this._next (C:\Users\enune\Documents\git\jhipster.primeng\generator-jhipster\node_modules\rxjs\dist\cjs\internal\operators\OperatorSubscriber.js:33:21)
    at Subscriber.next (C:\Users\enune\Documents\git\jhipster.primeng\generator-jhipster\node_modules\rxjs\dist\cjs\internal\Subscriber.js:51:18)
    at C:\Users\enune\Documents\git\jhipster.primeng\generator-jhipster\node_modules\rxjs\dist\cjs\internal\operators\mergeInternals.js:28:28
    at OperatorSubscriber._this._next (C:\Users\enune\Documents\git\jhipster.primeng\generator-jhipster\node_modules\rxjs\dist\cjs\internal\operators\OperatorSubscriber.js:33:21)
    at Subscriber.next (C:\Users\enune\Documents\git\jhipster.primeng\generator-jhipster\node_modules\rxjs\dist\cjs\internal\Subscriber.js:51:18)
    at C:\Users\enune\Documents\git\jhipster.primeng\generator-jhipster\node_modules\rxjs\dist\cjs\internal\observable\innerFrom.js:120:28
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by yelhouti** [comment]
@eanunezt try using jhipster import-jdl

**Comment by naris** [comment]
This happens when attempting to gtenerate a new application using jhipster. I ran into this attempting to generate an application using the release 8.0.0 version of jhipster (which I had to specify --skip-checks to do as it complains that this plugin targets only the beta1 version:
Welcome to JHipster v8.0.0
ERROR! An error occured while running jhipster:bootstrap#validateBlueprint
ERROR! ERROR! The installed generator-jhipster-primeng-blueprint blueprint targets JHipster v8.0.0-beta.1 and is not compatible with this JHipster version. Either update the blueprint or JHipster. You can also disable this check using --skip-checks at your own risk
Error: The installed generator-jhipster-primeng-blueprint blueprint targets JHipster v8.0.0-beta.1 and is not compatible with this JHipster version. Either update the blueprint or JHipster. You can also disable this check using --skip-checks at your own risk
    at BootstrapGenerator._checkJHipsterBlueprintVersion (file:///C:/Users/murwilso/AppData/Roaming/npm/node_modules/generator-jhipster/dist/generators/base/generator.mjs:550:19)
    at file:///C:/Users/murwilso/AppData/Roaming/npm/node_modules/generator-jhipster/dist/generators/bootstrap/generator.mjs:63:30
    at Array.forEach (<anonymous>)
    at BootstrapGenerator.validateBlueprint (file:///C:/Users/murwilso/AppData/Roaming/npm/node_modules/generator-jhipster/dist/generators/bootstrap/generator.mjs:62:52)
    at BootstrapGenerator.executeTask (file:///C:/Users/murwilso/AppData/Roaming/npm/node_modules/generator-jhipster/node_modules/yeoman-generator/dist/actions/lifecycle.js:244:26)
    at env.queueTask.once (file:///C:/Users/murwilso/AppData/Roaming/npm/node_modules/generator-jhipster/node_modules/yeoman-generator/dist/actions/lifecycle.js:218:56)
    at runLoop.add.once (file:///C:/Users/murwilso/AppData/Roaming/npm/node_modules/generator-jhipster/node_modules/yeoman-environment/dist/environment-base.js:381:23)
    at Immediate.<anonymous> (C:\Users\murwilso\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\grouped-queue\lib\subqueue.js:48:34)
    at process.processImmediate (node:internal/timers:478:21)

jhipster --skip-checks --blueprints primeng-blueprint
INFO! No custom commands found within blueprint: generator-jhipster-primeng-blueprint at C:\Users\murwilso\AppData\Roaming\npm\node_modules\generator-jhipster-primeng-blueprint

        ██╗ ██╗   ██╗ ████████╗ ███████╗   ██████╗ ████████╗ ████████╗ ███████╗
        ██║ ██║   ██║ ╚══██╔══╝ ██╔═══██╗ ██╔════╝ ╚══██╔══╝ ██╔═════╝ ██╔═══██╗
        ██║ ████████║    ██║    ███████╔╝ ╚█████╗     ██║    ██████╗   ███████╔╝
  ██╗   ██║ ██╔═══██║    ██║    ██╔════╝   ╚═══██╗    ██║    ██╔═══╝   ██╔══██║
  ╚██████╔╝ ██║   ██║ ████████╗ ██║       ██████╔╝    ██║    ████████╗ ██║  ╚██╗
   ╚═════╝  ╚═╝   ╚═╝ ╚═══════╝ ╚═╝       ╚═════╝     ╚═╝    ╚═══════╝ ╚═╝   ╚═╝
                            https://www.jhipster.tech
Welcome to JHipster v8.0.0

 _______________________________________________________________________________________________________________

? What is the base name of your application? jhipster
? Which *type* of application would you like to create? Monolithic application (recommended for simple projects)
? Besides Junit, which testing frameworks would you like to use? (Press <space> to select, <a> to toggle all, <i> to invert selection, and <enter> to proceed)
? Besides Junit, which testing frameworks would you like to use?
? Do you want to make it reactive with Spring WebFlux? No
? What is your default Java package name? com.mycompany.myapp
? Which *type* of authentication would you like to use? OAuth 2.0 / OIDC Authentication (stateful, works with Keycloak and Okta)
? Which *type* of database would you like to use? SQL (H2, PostgreSQL, MySQL, MariaDB, Oracle, MSSQL)
? Which *production* database would you like to use? Oracle
? Which *development* database would you like to use? Oracle
? Which cache do you want to use? (Spring cache abstraction) Infinispan (hybrid cache, for multiple nodes)
? Do you want to use Hibernate 2nd level cache? Yes
? Would you like to use Maven or Gradle for building the backend? Maven
? Which other technologies would you like to use? API first development using OpenAPI-generator
? Which *Framework* would you like to use for the client? Angular
? Besides Jest/Vitest, which testing frameworks would you like to use?
? Do you want to generate the admin UI? Yes
? Would you like to use a Bootswatch theme (https://bootswatch.com/)? Default JHipster
WARNING! Could not fetch bootswatch themes from API. Using default ones.
? Would you like to enable internationalization support? Yes
? Please choose the native language of the application English
ERROR! An error occured while running jhipster-primeng-blueprint:languages#askForLanguages
ERROR! ERROR! Cannot read properties of undefined (reading 'filter')
TypeError: Cannot read properties of undefined (reading 'filter')
    at Object.choices (file:///C:/Users/murwilso/AppData/Roaming/npm/node_modules/generator-jhipster-primeng-blueprint/node_modules/generator-jhipster/dist/generators/languages/prompts.mjs:58:59)
    at C:\Users\murwilso\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\run-async\index.js:91:25
    at new Promise (<anonymous>)
    at C:\Users\murwilso\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\run-async\index.js:32:19
    at Module.fetchAsyncQuestionProperty (file:///C:/Users/murwilso/AppData/Roaming/npm/node_modules/generator-jhipster/node_modules/@yeoman/adapter/node_modules/inquirer/lib/utils/utils.js:19:29)
    at file:///C:/Users/murwilso/AppData/Roaming/npm/node_modules/generator-jhipster/node_modules/@yeoman/adapter/node_modules/inquirer/lib/ui/prompt.js:94:17
    at doInnerSub (C:\Users\murwilso\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\@yeoman\adapter\node_modules\rxjs\dist\cjs\internal\operators\mergeInternals.js:22:31)
    at outerNext (C:\Users\murwilso\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\@yeoman\adapter\node_modules\rxjs\dist\cjs\internal\operators\mergeInternals.js:17:70)
    at OperatorSubscriber._this._next (C:\Users\murwilso\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\@yeoman\adapter\node_modules\rxjs\dist\cjs\internal\operators\OperatorSubscriber.js:33:21)
    at Subscriber.next (C:\Users\murwilso\AppData\Roaming\npm\node_modules\generator-jhipster\node_modules\@yeoman\adapter\node_modules\rxjs\dist\cjs\internal\Subscriber.js:51:18)

**Comment by yelhouti** [comment]
Sorry I don't have time yet to update to 8.0.0 and I also can't provide an ETA please feel free to contribute
